# Generated by Django 5.2.7 on 2025-10-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_devicedata_options_remove_devicedata_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='last_update_detailed_db',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='devicedata',
            name='last_update_relative_db',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='devicedata',
            name='relative_time_calculated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
